ty=""
evaluated="\\n:(Nat).(\\l:(mu X.<cons:{ Nat, X }, nil:Unit>).(fold [mu X.<cons:{ Nat, X }, nil:Unit>] <cons = {n,unfold [mu X.<cons:{ Nat, X }, nil:Unit>] l}> as mu X.<cons:{ Nat, X }, nil:Unit>))"
