[package]
name = "e2e_inference"
version = "0.1.0"
edition = "2021"

[[test]]
name = "inference"
path = "src/inference.rs"
harness=false

[dependencies]
serde = {version="1.0.219", features=["derive"]}

test_common = { path="../test_common" }
inference = { path="../../lang/inference" }
