use std::fmt;

/// Error getting example from the example select
/// generated by [`xtask`]
#[derive(Debug)]
pub struct UndefinedExample {
    /// Id in the example arrat
    ind: usize,
}

impl UndefinedExample {
    /// Create a new error from the index
    #[must_use]
    pub const fn new(ind: usize) -> Self {
        Self { ind }
    }
}

impl fmt::Display for UndefinedExample {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "No exmaple with id {}", self.ind)
    }
}

impl std::error::Error for UndefinedExample {}
