name="Times"
nameless="\\_.\\_.(1) (((\\_.\\_.\\_.\\_.(3) ((1) ((2) ((1) (0))))) (0)) (\\_.\\_.0))"
restored="\\x0.\\x1.(x0 ((\\x2.\\x3.\\x4.\\x5.(x2 (x4 (x3 (x4 x5)))) x1) \\x2.\\x3.x3))"
evaluated="\\m.\\n.(m) (((\\m.\\n.\\s.\\z.(m) ((s) ((n) ((s) (z))))) (n)) (\\s.\\z.z))"
