[package]
name = "latex"
version = "0.1.0"
edition = "2024"

[dependencies]
syntax={path="../syntax_lib"}
derivation={path="../derivation_lib"}
trace={path="../trace_lib"}
grammar={path="../grammar_lib"}
