ty="(Nat -> Bool)"
evaluated="\\n:Nat.(if (iszero(n)) { true } else { if (iszero(pred(n))) { false } else { (fix(\\f:(Nat -> Bool).(\\n:Nat.(if (iszero(n)) { true } else { if (iszero(pred(n))) { false } else { (f) (pred(n)) } })))) (pred(n)) } })"
