name="ResetCounterClass"
ty="({x:Ref[Nat]} -> {get:(Unit -> Nat), inc:(Unit -> Unit), reset:(Unit -> Unit)})"
evaluated="\\r:{x:Ref[Nat]}.(let (super = (counterclass) (r)) in {get=(super).get, inc=(super).inc, reset=\\_:Unit.(((r).x) := 1)})"
