ty="{ exists Counter, { get:(Counter) -> (Nat), inc:(Counter) -> (Counter), new:Counter } }"
evaluated="{*{ x:Nat },{ get = \\l:{ x:Nat }.(l.x), inc = \\l:{ x:Nat }.{ x = succ((l.x)) }, new = { x = succ(zero) } }} as { exists Counter, { get:(Counter) -> (Nat), inc:(Counter) -> (Counter), new:Counter } }"
