[package]
name = "web_check"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
web = { path = "../../../lib/web" }
errors = { path = "../../../lib/errors" }

wasm-bindgen = "0.2"
web-sys= { version="0.3", features=["Window"]}
