name="Add3"
ty="({exists X::*,{methods:{get:(X -> Nat), inc:(X -> X)}, state:X}} -> {exists X::*,{methods:{get:(X -> Nat), inc:(X -> X)}, state:X}})"
evaluated="\\c:{exists X::*,{methods:{get:(X -> Nat), inc:(X -> X)}, state:X}}.((inc) ((inc) ((inc) (c))))"
