name="Cons"
ty="forall X::*.(X -> (forall R::*.((X -> (R -> R)) -> (R -> R)) -> forall R::*.((X -> (R -> R)) -> (R -> R))))"
evaluated="\\X::*.\\hd:X.(\\tl:forall R::*.((X -> (R -> R)) -> (R -> R)).(\\R::*.(\\c:(X -> (R -> R)).(\\n:R.(((c) (hd)) (((((tl)[R])) (c)) (n)))))))"
