use std::fmt;

#[derive(Debug)]
pub enum EvaluationRule {
    AppAbs,
    Ascribe,
    Assign,
    Cast,
    Deref,
    Fold,
    Fst,
    Head,
    IfTrue,
    IfFalse,
    IsNilTrue,
    IsNilFalse,
    IsZeroTrue,
    IsZeroFalse,
    LetSubst,
    ListCaseNil,
    ListCaseCons,
    Pred,
    Projection,
    RecordProj,
    Ref,
    Snd,
    SomecaseSome,
    SomecaseNone,
    Succ,
    SumcaseLeft,
    SumcaseRight,
    Tail,
    TryCatch,
    TrySucc,
    TryValCatch,
    TryValSucc,
    TyAppAbs,
    TyAppAbsSub,
    UnfoldFold,
    UnpackPack,
    VariantCase,
    SubstName,
}

impl fmt::Display for EvaluationRule {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::AppAbs => f.write_str("E-AppAbs"),
            Self::Ascribe => f.write_str("E-Ascribe"),
            Self::Assign => f.write_str("E-Assign"),
            Self::Cast => f.write_str("E-Cast"),
            Self::Deref => f.write_str("E-Deref"),
            Self::Fold => f.write_str("E-Fold"),
            Self::Fst => f.write_str("E-Fst"),
            Self::Head => f.write_str("E-Head"),
            Self::IfTrue => f.write_str("E-If-True"),
            Self::IfFalse => f.write_str("E-If-False"),
            Self::IsNilTrue => f.write_str("E-IsNil-Nil"),
            Self::IsNilFalse => f.write_str("E-IsNil-Cons"),
            Self::IsZeroTrue => f.write_str("E-IsZero-Zero"),
            Self::IsZeroFalse => f.write_str("E-IsZero-Succ"),
            Self::LetSubst => f.write_str("E-Let"),
            Self::ListCaseNil => f.write_str("E-ListCase-Nil"),
            Self::ListCaseCons => f.write_str("E-ListCase-Cons"),
            Self::Pred => f.write_str("E-Pred"),
            Self::Projection => f.write_str("E-Projection"),
            Self::RecordProj => f.write_str("E-RecordProj"),
            Self::Ref => f.write_str("E-Ref"),
            Self::Snd => f.write_str("E-Snd"),
            Self::SomecaseSome => f.write_str("E-Somecase-Some"),
            Self::SomecaseNone => f.write_str("E-Somecase-None"),
            Self::Succ => f.write_str("E-Succ"),
            Self::SumcaseLeft => f.write_str("E-Sumcase-Left"),
            Self::SumcaseRight => f.write_str("E-Sumcase-Right"),
            Self::Tail => f.write_str("E-Tail"),
            Self::TryCatch => f.write_str("E-Try-Catch"),
            Self::TrySucc => f.write_str("E-Try"),
            Self::TryValCatch => f.write_str("E-TryVal-Catch"),
            Self::TryValSucc => f.write_str("E-TryVal"),
            Self::TyAppAbs => f.write_str("E-TyAppAbs"),
            Self::TyAppAbsSub => f.write_str("E-TyAppAbs-Sub"),
            Self::UnfoldFold => f.write_str("E-UnfoldFold"),
            Self::UnpackPack => f.write_str("E-UnpackPack"),
            Self::VariantCase => f.write_str("E-VariantCase"),
            Self::SubstName => f.write_str("E-SubstName"),
        }
    }
}
