name: 'Setup Environment'
description: 'Installs Rust and Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install Rust 
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Install Latex (Ubuntu)
      if: runner.os == 'Linux'
      run: sudo apt install -y texlive-full
      shell: bash
    - name: Install Latex (Mac)
      if: runner.os == "macOS"
      run: brew install --cask mactex
      shell: bash
