name: 'Setup Environment'
description: 'Installs Rust and Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install Rust 
      uses: dtolnay/rust-toolchain@stable
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Install Latex
      run: sudo apt install -y texlive-xetex
      shell: bash
