name="SumList"
ty="(mu X.<cons_:(Nat x X), nil_:Unit> -> Nat)"
evaluated="\\l:mu X.<cons_:(Nat x X), nil_:Unit>.(if ((isnil_) (l)) { 0 } else { ((plus) ((head_) (l))) ((fix(\\s:(mu X.<cons_:(Nat x X), nil_:Unit> -> Nat).(\\l:mu X.<cons_:(Nat x X), nil_:Unit>.(if ((isnil_) (l)) { 0 } else { ((plus) ((head_) (l))) ((s) ((tail_) (l))) })))) ((tail_) (l))) })"
