[package]
name = "tapl"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tapl"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features=["derive"]}
common = { path="../lang/common" }
languages= {path="../lang/languages"}
