ty="{exists Counter::*,{get:(Counter -> Nat), inc:(Counter -> Counter), new:Counter}}"
evaluated="{*Nat,{get=\\i:Nat.(i), inc=\\i:Nat.(succ(i)), new=1}} as {exists Counter::*,{get:(Counter -> Nat), inc:(Counter -> Counter), new:Counter}}"
