name="BackupCounterClass"
ty="({b:Ref[Nat], x:Ref[Nat]} -> {backup:(Unit -> Unit), get:(Unit -> Nat), inc:(Unit -> Unit), reset:(Unit -> Unit)})"
evaluated="\\r:{b:Ref[Nat], x:Ref[Nat]}.(let (super = (resetcounterclass) (r)) in {backup=\\_:Unit.(((r).b) := !(r).x), get=(super).get, inc=(super).inc, reset=\\_:Unit.(((r).x) := !(r).b)})"
