[package]
name = "language_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
common={ path="../common_lib" }
language_core={path="../language_core_lib"}
pest={version="2.7.15"}
pest_derive={version="2.7.15"}
