name="FixD"
ty="mu X.(X -> X)"
evaluated="fold[mu X.(X -> X)](\\f:mu X.(X -> X).(((ap) ((lam) (\\x:mu X.(X -> X).(((ap) (f)) (((ap) (x)) (x)))))) ((lam) (\\x:mu X.(X -> X).(((ap) (f)) (((ap) (x)) (x)))))))"

