name="Process"
ty="mu A.(Nat -> (Nat x A))"
evaluated="fold[mu A.(Nat -> (Nat x A))](\\n:Nat.(let (newacc = ((plus) (0)) (n)) in { newacc, (fix(\\f:(Nat -> mu A.(Nat -> (Nat x A))).(\\acc:Nat.(fold[mu A.(Nat -> (Nat x A))](\\n:Nat.(let (newacc = ((plus) (acc)) (n)) in { newacc, (f) (newacc) })))))) (newacc) }))"
