name="UpFromZero"
ty="mu A.(Unit -> (Nat x A))"
evaluated="fold[mu A.(Unit -> (Nat x A))](\\_:Unit.({ 0, (fix(\\f:(Nat -> mu A.(Unit -> (Nat x A))).(\\n:Nat.(fold[mu A.(Unit -> (Nat x A))](\\_:Unit.({ n, (f) (succ(n)) })))))) (succ(0)) }))"
