ty="mu A.(Unit) -> ({ Nat, A })"
evaluated="fold [mu A.(Unit) -> ({ Nat, A })] \\_:(Unit).({zero,((fix (\\f:((Nat) -> (mu A.(Unit) -> ({ Nat, A }))).(\\n:(Nat).(fold [mu A.(Unit) -> ({ Nat, A })] \\_:(Unit).({n,((f) (succ(n)))}))))) (succ(zero)))})"
