ty="(mu X.<cons:{ Nat, X }, nil:Unit>) -> (mu X.<cons:{ Nat, X }, nil:Unit>)"
evaluated="\\l:(mu X.<cons:{ Nat, X }, nil:Unit>).(case unfold [mu X.<cons:{ Nat, X }, nil:Unit>] l of { <nil=u> => l| <cons=p> => p.1 })"
