ty="(mu X.<cons:(Nat x X), nil:Unit> -> mu X.<cons:(Nat x X), nil:Unit>)"
evaluated="\\l:mu X.<cons:(Nat x X), nil:Unit>.(case unfold[mu X.<cons:(Nat x X), nil:Unit>](l) of { <cons = p> => (p).1| <nil = u> => l })"
