use std::fmt;

#[derive(Debug)]
pub enum TypingRule {
    App,
    Ascribe,
    Assign,
    Cast,
    Cons,
    Deref,
    Exception,
    Fix,
    False,
    Fold,
    Fst,
    Head,
    If,
    IsNil,
    IsZero,
    Lambda,
    LambdaSub,
    Left,
    Let,
    ListCase,
    Loc,
    Nil,
    Nothing,
    Num,
    Pack,
    PackBound,
    Pair,
    Pred,
    Projection,
    Raise,
    Record,
    RecordProj,
    Ref,
    Right,
    Snd,
    SomeCase,
    Something,
    Succ,
    SumCase,
    Tail,
    True,
    Try,
    TryVal,
    Tuple,
    TyApp,
    TyAppBounded,
    TyLambda,
    Unfold,
    Unit,
    Unpack,
    UnpackBounded,
    Variable,
    Variant,
    VariantCase,
    Empty,
}

impl fmt::Display for TypingRule {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            Self::App => f.write_str("T-App"),
            Self::Ascribe => f.write_str("T-Ascribe"),
            Self::Assign => f.write_str("T-Assign"),
            Self::Cast => f.write_str("T-Cast"),
            Self::Cons => f.write_str("T-Cons"),
            Self::Deref => f.write_str("T-Deref"),
            Self::Exception => f.write_str("T-Err"),
            Self::Fix => f.write_str("T-Fix"),
            Self::False => f.write_str("T-False"),
            Self::Fold => f.write_str("T-Fold"),
            Self::Fst => f.write_str("T-Fst"),
            Self::Head => f.write_str("T-Head"),
            Self::If => f.write_str("T-If"),
            Self::IsNil => f.write_str("T-IsNil"),
            Self::IsZero => f.write_str("T-IsZero"),
            Self::Lambda => f.write_str("T-Lambda"),
            Self::LambdaSub => f.write_str("T-Lambda<:"),
            Self::Left => f.write_str("T-Left"),
            Self::Let => f.write_str("T-Let"),
            Self::ListCase => f.write_str("T-ListCase"),
            Self::Loc => f.write_str("T-Loc"),
            Self::Nil => f.write_str("T-Nil"),
            Self::Nothing => f.write_str("T-Nothing"),
            Self::Num => f.write_str("T-Int"),
            Self::Pack => f.write_str("T-Pack"),
            Self::PackBound => f.write_str("T-Pack<:"),
            Self::Pair => f.write_str("T-Pair"),
            Self::Pred => f.write_str("T-Pred"),
            Self::Projection => f.write_str("T-Proj"),
            Self::Raise => f.write_str("T-Raise"),
            Self::Record => f.write_str("T-Record"),
            Self::RecordProj => f.write_str("T-RecordProj"),
            Self::Ref => f.write_str("T-Ref"),
            Self::Right => f.write_str("T-Right"),
            Self::Snd => f.write_str("T-Snd"),
            Self::SomeCase => f.write_str("T-SomeCase"),
            Self::Something => f.write_str("T-Something"),
            Self::Succ => f.write_str("T-Succ"),
            Self::SumCase => f.write_str("T-SumCase"),
            Self::Tail => f.write_str("T-Tail"),
            Self::True => f.write_str("T-True"),
            Self::Try => f.write_str("T-Try"),
            Self::TryVal => f.write_str("T-TryV"),
            Self::Tuple => f.write_str("T-Tuple"),
            Self::TyApp => f.write_str("T-TyApp"),
            Self::TyAppBounded => f.write_str("T-TyApp<:"),
            Self::TyLambda => f.write_str("T-OpAbs"),
            Self::Unfold => f.write_str("T-Unfold"),
            Self::Unit => f.write_str("T-Unit"),
            Self::Unpack => f.write_str("T-Unpack"),
            Self::UnpackBounded => f.write_str("T-Unpack<:"),
            Self::Variable => f.write_str("T-Var"),
            Self::Variant => f.write_str("T-Variant"),
            Self::VariantCase => f.write_str("T-VariantCase"),
            Self::Empty => f.write_str(""),
        }
    }
}
