[package]
name = "tapl_cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tapl_cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features=["derive"]}
errors = { path="../error_lib" }
language = {path="../language_lib"}
grammar = {path="../grammar_lib"}
