[package]
name = "tapl_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tapl_cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features=["derive"]}
common = { path="../common_lib" }
language_impl = {path="../language_impl_lib"}
