name="NewDecCounter"
ty="({x:Ref[Nat]} -> {dec:(Nat -> Unit), get:(Unit -> Nat), inc:(Unit -> Unit), reset:(Unit -> Unit)})"
evaluated="\\r:{x:Ref[Nat]}.(let (super = (resetcounterclass) (r)) in {dec=\\n:Nat.(((r).x) := pred(!(r).x)), get=(super).get, inc=(super).inc, reset=(super).reset})"
