name: Rust CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: cargo check --all

  ubuntu-tests:
    name: Tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: make test 

  macos-tests:
    name: Tests (Mac)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: make test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: rustup component add clippy
      - run: cargo clippy --all -- -D warnings
