name: Deploy GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  statuses: write
  pages: write 
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-env
      - run: |
          cargo install wasm-pack
          make web VERBOSE=1
      - uses: actions/upload-pages-artifact@v3
        with:
          path: html/
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
