ty="(\\M<:Top[(*) => (*)].{exists X<:Top[*],{methods:(M[X]), state:X}}[\\R<:Top[*].{get:(R -> Nat), inc:(R -> R)}])"
evaluated="{*{x:Nat},{methods={get=\\r:{x:Nat}.((r).x), inc=\\r:{x:Nat}.({x=succ((r).x)})}, state={x=0}}} as (\\M<:Top[(*) => (*)].{exists X<:Top[*],{methods:(M[X]), state:X}}[\\R<:Top[*].{get:(R -> Nat), inc:(R -> R)}])"
